#!/usr/bin/env bash

if [ $# -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 0
fi
PATH=$1
IP=$2
USER=$3
KEY_PATH=$4

/usr/bin/scp -i "$KEY_PATH" -o "StrictHostKeyChecking=no" "$PATH" "$USER@$IP:~/"
