#!/usr/bin/env bash
# configure Nginx server to meet certain requirements

# update my packets
sudo apt-get update

#install Nginx
sudo apt-get install -y nginx

# create index.html file in /var/www/html/ with
# appropriate content

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

echo "server {
	listen 80;
	listen [::]:80;

	server_name _;

	location / {
		root /var/www/html;
		index index.html index.htm;
	}
}" | sudo tee /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
