#!/usr/bin/env bash
# configure Nginx server to meet certain requirements

# update my packets
sudo apt-get update

#install Nginx
sudo apt-get install -y nginx

# create index.html file in /var/www/html/ with
# appropriate content

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "301 Moved Permanently" | sudo tee /var/www/html/redirect_me.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

echo "server {
	listen 80;
	listen [::]:80;

	server_name _;

	location / {
		root /var/www/html;
		index index.html index.htm;
	}
}" | sudo tee /etc/nginx/sites-available/default

DIR="/var/www/html/redirect_me.html"
NGINX="/etc/nginx/sites-available/default"

sudo cp "$NGINX" "$NGINX.bak"

sudo sed -i "/server_name.*;/i \\
        error_page 404 /custom_404.html;\\
        location = /custom_404.html {\\
            internal;\\
            root /var/www/html;\\
            index index.html;\\
            try_files \$uri \$uri/ /index.html;\\
        }" "$NGINX"

sudo sed -i "/server_name*;/i \ \ \ \ location \/redirect_me {\n \ \ \ \ \ \ \ return 301 $DIR;\n \ \ \ \ \ }\n" "$NGINX"

sudo nginx -t

sudo service nginx restart
