#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt update

#sudo apt-get install -y --no-install-recommends software-properties-common

#sudo add-apt-repository ppa:vbernat/haproxy-2.8

sudo apt-get install -y haproxy=2.8.\*

sudo echo "ENABLED=1" | tee -a /etc/default/haproxy

sudo echo "CONFIG=/etc/haproxy/haproxy.cfg" | tee -a /etc/default/haproxy

sudo echo "
frontend front
	bind *:80
	default_backend backend

backend backend
	balance roundrobin
	server 208065-web-01 100.26.236.29:80 check
	server 208065-web-02 100.26.216.44:80 check" | tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
