#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt update

sudo apt-get install -y --no-install-recommends software-properties-common

sudo add-apt-repository ppa:vbernat/haproxy-2.8

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo "CONFIG=/etc/haproxy/haproxy.cfg" | sudo tee -a /etc/default/haproxy

sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend front
	bind *:80
	default_backend backend

backend backend
	balance roundrobin
	server 208065-web-01 100.26.236.29:80 check
	server 208065-web-02 100.26.216.44:80 check
EOF

sudo service haproxy restart
