#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it"""

if [ $# -ne 1 ]; then
	echo "Usage: ./5-mysql_backup <mysql_password>"
	exit 1
fi

dump_file="backup.sql"

archive_name="$(date +'%d-%m-%y').tar.gz"

mysqldump -u root -p'$1' --all-databases > $dump_file

if [ $? -eq 0 ]; then
	tar -czf "$archive_name" "$dump_file"
fi
