#!/usr/bin/env bash
# This script re-configures a Ubuntu server

cp /etc/hosts ~/hosts.new
sed -i -e '$a\8.8.8.8		facebook.com' ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
